import { z } from "zod";

/** IDs are generated by Prisma, but requests only need a non-empty value. */
export const idSchema = z.string().trim().min(1);

export const organizationIdSchema = z.object({
    orgId: idSchema,
});

export const boardIdSchema = z.object({
    boardId: idSchema,
});

export const sectionIdSchema = z.object({
    sectionId: idSchema,
});

export const issueIdSchema = z.object({
    issueId: idSchema,
});

export const commentIdSchema = z.object({
    commentId: idSchema,
});
